### ISSUE TITLE
No connections

### ISSUE THREAD

**Issue by Whitesun123** [OneParsec/njRAT#1]
Hello, I just want to ask if I'm the only one having problems with the client not connecting to the server.

**Comment by OneParsec** [comment]
What njRAT version do you use?

**Comment by Whitesun123** [comment]
0.7D dangerous edition. Quasar RAT works normally but njRAT, LimeRAT, Warzone, Orcus dont

**Comment by OneParsec** [comment]
Dangerous version is unstable, so use Golden or Green version

**Comment by lo228** [comment]
Все версии NGrat работаю на 10 виндовс или только для страрых?
